// lib/staffStore.ts
import { useEffect, useState } from "react";
import g1 from "@/assets/gallery-1.jpg";
import g2 from "@/assets/gallery-2.jpg";
import g3 from "@/assets/gallery-3.jpg";
import g4 from "@/assets/gallery-4.jpg";
import g5 from "@/assets/gallery-5.jpg";
import g6 from "@/assets/gallery-6.jpg";
import g7 from "@/assets/gallery-7.jpg";
import g8 from "@/assets/gallery-8.jpg";

// lib/staffStore.ts
export interface StaffMember {
  id: string;
  name: string;
  designation: string;
  education: string;
  year: string;
  photo: string;
  mobile: string;
  email: string;
  // Teaching staff fields
  teacherCode: string;
  dob: string;
  registrationNumber: string;
  qualification: string;
  dateOfJoining: string;
  experience: string;
  // Non-teaching & Hospital staff fields
  fatherName?: string;
  dateOfAppointment?: string;
  natureOfAppointment?: string;
  workingDepartment?: string;
  payScale?: string;
  employeeNumber?: string;
}

export type StaffGroupKey = "hospital" | "non-teaching" | "teaching";

export const STAFF_GROUPS: { key: StaffGroupKey; label: string }[] = [
  { key: "hospital", label: "Hospital Staff" },
  { key: "non-teaching", label: "Non-Teaching Staff" },
  { key: "teaching", label: "Teaching Staff" },
];

const P = [g1, g2, g3, g4, g5, g6, g7, g8];

const DEFAULTS: Record<StaffGroupKey, StaffMember[]> = {
  hospital: [
  {
    id: "h1",
    name: "Dr. Divthane Prashant Janardhan",
    fatherName: "Janardhan",
    qualification: "BAMS, MS(Shalakyatantra)",
    dateOfAppointment: "15-12-2025",
    natureOfAppointment: "regular",
    designation: "Medical Superintendent",
    department: "Hospital Staff",
    payScale: "43000-67000 GP 10000",
    photo: P[0],
  },
  {
    id: "h2",
    name: "Dr. Metangale Bhagwan Madhavrao",
    fatherName: "Madhavrao",
    qualification: "BAMS, MS",
    dateOfAppointment: "01-07-2024",
    natureOfAppointment: "regular",
    designation: "Deputy Medical Superintendent",
    department: "Hospital Staff",
    payScale: "15600-39100 GP 6000",
    photo: P[1],
  },
  {
    id: "h3",
    name: "Dr. Khokale Ramkrushna Bhagwat",
    fatherName: "Bhagwat",
    qualification: "BAMS, MD(Balrog)",
    dateOfAppointment: "02-01-2023",
    natureOfAppointment: "regular",
    designation: "Consultant / Clinical Teacher",
    department: "Hospital Staff",
    payScale: "15600-39100 GP 6000",
    photo: P[2],
  },
  {
    id: "h4",
    name: "Dr. Iregaonkar Roshan Shivappa",
    fatherName: "Shivappa",
    qualification: "BAMS, MS(Shalakya)",
    dateOfAppointment: "02-01-2023",
    natureOfAppointment: "regular",
    designation: "Consultant / Clinical Teacher",
    department: "Hospital Staff",
    payScale: "15600-39100 GP 6000",
    photo: P[3],
  },
  {
    id: "h5",
    name: "Dr. Bonde Sharayu Rajendra",
    fatherName: "Rajendra",
    qualification: "BAMS, MS (Shalya)",
    dateOfAppointment: "20-09-2023",
    natureOfAppointment: "regular",
    designation: "Consultant / Clinical Teacher",
    department: "Hospital Staff",
    payScale: "15600-39100 GP 6000",
    photo: P[4],
  },
  {
    id: "h6",
    name: "Dr. Davhale Om Dattatray",
    fatherName: "Dattatray",
    qualification: "BAMS, MD(Panchakarma)",
    dateOfAppointment: "17-03-2026",
    natureOfAppointment: "regular",
    designation: "Consultant / Clinical Teacher",
    department: "Hospital Staff",
    payScale: "15600-39100 GP 6000",
    photo: P[5],
  },
  {
    id: "h7",
    name: "Dr. Thakare Nilesh Dagaduji",
    fatherName: "Dagaduji",
    qualification: "BAMS, MS(Strirog & PST)",
    dateOfAppointment: "02-01-2023",
    natureOfAppointment: "regular",
    designation: "Consultant / Clinical Teacher",
    department: "Hospital Staff",
    payScale: "15600-39100 GP 6000",
    photo: P[6],
  },
  {
    id: "h8",
    name: "Dr. Narwade Sachin Parmeshwar",
    fatherName: "Parmeshwar",
    qualification: "BAMS, MD(Kayachikitsa)",
    dateOfAppointment: "02-01-2023",
    natureOfAppointment: "regular",
    designation: "Consultant / Clinical Teacher",
    department: "Hospital Staff",
    payScale: "15600-39100 GP 6000",
    photo: P[7],
  },
  {
    id: "h9",
    name: "Dr. Shendge Pallavi Sudhir",
    fatherName: "Sudhir",
    qualification: "BAMS, MD(Swasthavritta)",
    dateOfAppointment: "16-03-2026",
    natureOfAppointment: "regular",
    designation: "Consultant / Clinical Teacher",
    department: "Hospital Staff",
    payScale: "15600-39100 GP 6000",
    photo: P[0],
  },
  {
    id: "h10",
    name: "Dr. Deshmukh Dhananjay Wamanrao",
    fatherName: "Wamanrao",
    qualification: "BAMS, MD(Agadtantra)",
    dateOfAppointment: "01-01-2025",
    natureOfAppointment: "regular",
    designation: "Consultant / Clinical Teacher",
    department: "Hospital Staff",
    payScale: "15600-39100 GP 6000",
    photo: P[1],
  },
  {
    id: "h11",
    name: "Dr. Jodpe Ankita Sunil",
    fatherName: "Sunil",
    qualification: "BAMS",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "RMO (Resident Medical Officer)",
    department: "Hospital Staff",
    payScale: "9300-34800 GP 5400",
    photo: P[2],
  },
  {
    id: "h12",
    name: "Dr. Borade Pankaj Devidas",
    fatherName: "Devidas",
    qualification: "BAMS",
    dateOfAppointment: "01-07-2023",
    natureOfAppointment: "regular",
    designation: "Emergency Medical Officer",
    department: "Hospital Staff",
    payScale: "9300-34800 GP 5400",
    photo: P[3],
  },
  {
    id: "h13",
    name: "Kamble Kiran Balaji",
    fatherName: "Balaji",
    qualification: "GNM",
    dateOfAppointment: "03-11-2018",
    natureOfAppointment: "regular",
    designation: "Matron or Nursing Superintendent",
    department: "Hospital Staff",
    payScale: "9300-34800 GP 4400",
    photo: P[4],
  },
  {
    id: "h14",
    name: "Mhaske Manisha Rameshwar",
    fatherName: "Rameshwar",
    qualification: "ANM",
    dateOfAppointment: "01-04-2026",
    natureOfAppointment: "regular",
    designation: "Assistant Matron",
    department: "Hospital Staff",
    payScale: "9300-34800 GP 4400",
    photo: P[5],
  },
  {
    id: "h15",
    name: "Bhise Pooja Sanjay",
    fatherName: "Sanjay",
    qualification: "ANM",
    dateOfAppointment: "01-04-2026",
    natureOfAppointment: "regular",
    designation: "Assistant Matron",
    department: "Hospital Staff",
    payScale: "9300-34800 GP 4400",
    photo: P[6],
  },
  {
    id: "h16",
    name: "Dr. Dhote Harshal Nitesh",
    fatherName: "Nitesh",
    qualification: "M.Pharm",
    dateOfAppointment: "01-04-2026",
    natureOfAppointment: "regular",
    designation: "Office Superintendent",
    department: "Hospital Staff",
    payScale: "9300-34800 GP 5400",
    photo: P[7],
  },
  {
    id: "h17",
    name: "Naykal Suhas Sureshrao",
    fatherName: "Sureshrao",
    qualification: "B.Com",
    dateOfAppointment: "24-01-2025",
    natureOfAppointment: "regular",
    designation: "Accountant",
    department: "Hospital Staff",
    payScale: "9300-34800 GP 4200",
    photo: P[0],
  },
  {
    id: "h18",
    name: "Dolas Purushottam Janardhan",
    fatherName: "Janardhan",
    qualification: "BA",
    dateOfAppointment: "05-01-2018",
    natureOfAppointment: "regular",
    designation: "Store Keeper",
    department: "Hospital Staff",
    payScale: "5200-20200 GP 2400",
    photo: P[1],
  },
  {
    id: "h19",
    name: "Sardar Sushil Narayan",
    fatherName: "Narayan",
    qualification: "HSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "MTS",
    department: "Hospital Staff",
    payScale: "4440-7440 GP 1300",
    photo: P[2],
  },
  {
    id: "h20",
    name: "Takalkar Shankar Madhukar",
    fatherName: "Madhukar",
    qualification: "B.A",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "MTS",
    department: "Hospital Staff",
    payScale: "4440-7440 GP 1300",
    photo: P[3],
  },
  {
    id: "h21",
    name: "Padmane Sanjay Pandurang",
    fatherName: "Pandurang",
    qualification: "ITI",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "MTS",
    department: "Hospital Staff",
    payScale: "5200-20200 GP 2400",
    photo: P[4],
  },
  {
    id: "h22",
    name: "Dr. Rajguru Utkarsha Subhash",
    fatherName: "Subhash",
    qualification: "BAMS",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Medical Officer",
    department: "Hospital Staff",
    payScale: "9300-34800 GP 5400",
    photo: P[5],
  },
  {
    id: "h23",
    name: "Dr. Katrale Sonal Balasaheb",
    fatherName: "Balasaheb",
    qualification: "MBBS, MD",
    dateOfAppointment: "01-07-2024",
    natureOfAppointment: "Part Time",
    designation: "Anaesthesiologist",
    department: "Modern Medical Staff",
    payScale: "14000/- Fix",
    photo: P[6],
  },
  {
    id: "h24",
    name: "Dr. Shinde Pratibha Tejrao",
    fatherName: "Tejrao",
    qualification: "MBBS, MD",
    dateOfAppointment: "01-07-2024",
    natureOfAppointment: "Part Time",
    designation: "Pathologist",
    department: "Modern Medical Staff",
    payScale: "14000/- Fix",
    photo: P[7],
  },
  {
    id: "h25",
    name: "Dr. Kale Om Vijay",
    fatherName: "Vijay",
    qualification: "DMRE",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "Part Time",
    designation: "Radiologist",
    department: "Modern Medical Staff",
    payScale: "14000/- Fix",
    photo: P[0],
  },
  {
    id: "h26",
    name: "Dabhade Bharati Ramesh",
    fatherName: "Ramesh",
    qualification: "HSC",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Receptionist",
    department: "Reception & Registration",
    payScale: "9300-34800 GP 4200",
    photo: P[1],
  },
  {
    id: "h27",
    name: "Dutonde Gajanan Ashok",
    fatherName: "Ashok",
    qualification: "D.Ed",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Registration / Billing Clerk",
    department: "Reception & Registration",
    payScale: "9300-34800 GP 4200",
    photo: P[2],
  },
  {
    id: "h28",
    name: "Sable Pooja Bhaurao",
    fatherName: "Bhaurao",
    qualification: "B.Pharm",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Registration / Billing Clerk",
    department: "Reception & Registration",
    payScale: "5200-20200 GP 1900",
    photo: P[3],
  },
  {
    id: "h29",
    name: "Pakhale Manoj Machhindra",
    fatherName: "Machhindra",
    qualification: "B.A.",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Medical Record Technician",
    department: "Reception & Registration",
    payScale: "5200-20200 GP 1900",
    photo: P[4],
  },
  {
    id: "h30",
    name: "Rajguru Rohini Dattatray",
    fatherName: "Dattatray",
    qualification: "ANM",
    dateOfAppointment: "03-11-2018",
    natureOfAppointment: "regular",
    designation: "Staff Nurse",
    department: "OPD",
    payScale: "9300-34800 GP 4200",
    photo: P[5],
  },
  {
    id: "h31",
    name: "Pawar Laxmi Madan",
    fatherName: "Madan",
    qualification: "ANM",
    dateOfAppointment: "03-11-2018",
    natureOfAppointment: "regular",
    designation: "Staff Nurse",
    department: "OPD",
    payScale: "9300-34800 GP 4200",
    photo: P[6],
  },
  {
    id: "h32",
    name: "Rankhamb Laxmi Ratan",
    fatherName: "Ratan",
    qualification: "ANM",
    dateOfAppointment: "06-11-2018",
    natureOfAppointment: "regular",
    designation: "Staff Nurse",
    department: "OPD",
    payScale: "9300-34800 GP 4200",
    photo: P[7],
  },
  {
    id: "h33",
    name: "Sahu Archana Vinod",
    fatherName: "Vinod",
    qualification: "HSC",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Ayah",
    department: "OPD",
    payScale: "4440-7440 GP 1300",
    photo: P[0],
  },
  {
    id: "h34",
    name: "Dikhit Diksha Singh Devendra",
    fatherName: "Devendra",
    qualification: "HSC",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Ayah",
    department: "OPD",
    payScale: "4440-7440 GP 1300",
    photo: P[1],
  },
  {
    id: "h35",
    name: "Takalkar Rupali Shankar",
    fatherName: "Shankar",
    qualification: "HSC",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Ayah",
    department: "OPD",
    payScale: "4440-7440 GP 1300",
    photo: P[2],
  },
  {
    id: "h36",
    name: "Hade Payal Sanjay",
    fatherName: "Sanjay",
    qualification: "D.Pharm",
    dateOfAppointment: "09-11-2018",
    natureOfAppointment: "regular",
    designation: "Pharmacist",
    department: "Medical Dispensary",
    payScale: "9300-34800 GP 5400",
    photo: P[3],
  },
  {
    id: "h37",
    name: "Ingle Bhavana Vinod",
    fatherName: "Vinod",
    qualification: "B.Pharm",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Pharmacist",
    department: "Medical Dispensary",
    payScale: "9300-34800 GP 5400",
    photo: P[4],
  },
  {
    id: "h38",
    name: "Gaikwad Rushikesh Vinod",
    fatherName: "Vinod",
    qualification: "B.Sc",
    dateOfAppointment: "21-09-2025",
    natureOfAppointment: "regular",
    designation: "Laboratory Technician",
    department: "Diagnostic Zone",
    payScale: "9300-34800 GP 4200",
    photo: P[5],
  },
  {
    id: "h39",
    name: "Dhande Ankit Dinkar",
    fatherName: "Dinkar",
    qualification: "B.Sc",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Laboratory Technician",
    department: "Diagnostic Zone",
    payScale: "9300-34800 GP 4200",
    photo: P[6],
  },
  {
    id: "h40",
    name: "Deshmukh Jabir Haidarkhan",
    fatherName: "Haidarkhan",
    qualification: "HSC",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Peon or Attendent",
    department: "Diagnostic Zone",
    payScale: "4440-7440 GP 1300",
    photo: P[7],
  },
  {
    id: "h41",
    name: "Kadbhane Sagar Dilip",
    fatherName: "Dilip",
    qualification: "Diploma In X-Ray Tech",
    dateOfAppointment: "03-10-2023",
    natureOfAppointment: "regular",
    designation: "X-Ray Technician or Radiographer",
    department: "Diagnostic Zone",
    payScale: "14000 /- Fix",
    photo: P[0],
  },
  {
    id: "h42",
    name: "Paraskar Dipak Ramesh",
    fatherName: "Ramesh",
    qualification: "B.Sc",
    dateOfAppointment: "09-11-2018",
    natureOfAppointment: "regular",
    designation: "Dark Room Attendent",
    department: "Diagnostic Zone",
    payScale: "4440-7440 GP 1300",
    photo: P[1],
  },
  {
    id: "h43",
    name: "Chaudhari Pravin Raju",
    fatherName: "Raju",
    qualification: "Diploma In ECG Tech",
    dateOfAppointment: "01-04-2026",
    natureOfAppointment: "regular",
    designation: "ECG Technician",
    department: "Diagnostic Zone",
    payScale: "9300-34800 GP 4200",
    photo: P[2],
  },
  {
    id: "h44",
    name: "Pise Mahesh Vishnu",
    fatherName: "Vishnu",
    qualification: "M.Sc (Microbiology)",
    dateOfAppointment: "01-04-2026",
    natureOfAppointment: "Part Time",
    designation: "Microbiologist",
    department: "Diagnostic Zone",
    payScale: "9300-34800 GP 4200",
    photo: P[3],
  },
  {
    id: "h45",
    name: "Umalkar Dikshya Sanjay",
    fatherName: "Sanjay",
    qualification: "ANM",
    dateOfAppointment: "05-11-2018",
    natureOfAppointment: "regular",
    designation: "Staff Nurse",
    department: "Medical IPD",
    payScale: "9300-34800 GP 4200",
    photo: P[4],
  },
  {
    id: "h46",
    name: "Dongre Ashwini Ramsing",
    fatherName: "Ramsing",
    qualification: "ANM",
    dateOfAppointment: "01-01-2021",
    natureOfAppointment: "regular",
    designation: "Staff Nurse",
    department: "Medical IPD",
    payScale: "9300-34800 GP 4200",
    photo: P[5],
  },
  {
    id: "h47",
    name: "Sonune Surekha Ramkisan",
    fatherName: "Ramkisan",
    qualification: "ANM",
    dateOfAppointment: "05-11-2018",
    natureOfAppointment: "regular",
    designation: "Staff Nurse",
    department: "Medical IPD",
    payScale: "9300-34800 GP 4200",
    photo: P[6],
  },
  {
    id: "h48",
    name: "Trayambake Sharda Dnyanba",
    fatherName: "Dnyanba",
    qualification: "ANM",
    dateOfAppointment: "09-11-2018",
    natureOfAppointment: "regular",
    designation: "Staff Nurse",
    department: "Medical IPD",
    payScale: "9300-34800 GP 4200",
    photo: P[7],
  },
  {
    id: "h49",
    name: "Sadawarte Hemant Arjun",
    fatherName: "Arjun",
    qualification: "B.F.A",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "MTS",
    department: "Medical IPD",
    payScale: "5200-20200 GP 1900",
    photo: P[0],
  },
  {
    id: "h50",
    name: "Shaikh Irfan Shaikh Rajjak",
    fatherName: "Rajjak",
    qualification: "B.A.",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "MTS",
    department: "Medical IPD",
    payScale: "9300-34800 GP 4200",
    photo: P[1],
  },
  {
    id: "h51",
    name: "Dr. Kadhane Dhiraj Atmaram",
    fatherName: "Atmaram",
    qualification: "BAMS",
    dateOfAppointment: "01-06-2025",
    natureOfAppointment: "regular",
    designation: "RMO (Resident Medical Officer)",
    department: "Medical IPD",
    payScale: "9300-34800 GP 5400",
    photo: P[2],
  },
  {
    id: "h52",
    name: "Dr. Kulsundar Puja Shridhar",
    fatherName: "Shridhar",
    qualification: "BAMS",
    dateOfAppointment: "12-07-2024",
    natureOfAppointment: "regular",
    designation: "Emergency Medical Officer",
    department: "Medical IPD",
    payScale: "9300-34800 GP 5400",
    photo: P[3],
  },
  {
    id: "h53",
    name: "Chole Babasaheb Bhagwan",
    fatherName: "Bhagwan",
    qualification: "GNM",
    dateOfAppointment: "03-11-2018",
    natureOfAppointment: "regular",
    designation: "Staff Nurse",
    department: "Surgical IPD",
    payScale: "9300-34800 GP 4200",
    photo: P[4],
  },
  {
    id: "h54",
    name: "Prajapat Rahul Phoolchandkumar",
    fatherName: "Phoolchandkumar",
    qualification: "ANM",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Staff Nurse",
    department: "Surgical IPD",
    payScale: "9300-34800 GP 4200",
    photo: P[5],
  },
  {
    id: "h55",
    name: "Bhandwale Pooja Pandurang",
    fatherName: "Pandurang",
    qualification: "ANM",
    dateOfAppointment: "01-04-2026",
    natureOfAppointment: "regular",
    designation: "Staff Nurse",
    department: "Surgical IPD",
    payScale: "9300-34800 GP 4200",
    photo: P[6],
  },
  {
    id: "h56",
    name: "Raut Ashok Manikrao",
    fatherName: "Manikrao",
    qualification: "HSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "MTS",
    department: "Surgical IPD",
    payScale: "4440-7440 GP 1880",
    photo: P[7],
  },
  {
    id: "h57",
    name: "Chopade Rahul Dilip",
    fatherName: "Dilip",
    qualification: "HSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "MTS",
    department: "Surgical IPD",
    payScale: "4440-7440 GP 1880",
    photo: P[0],
  },
  {
    id: "h58",
    name: "Dr. Nagrik Mayuri Sudhakar",
    fatherName: "Diliprao",
    qualification: "BAMS",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "RSO (Surgical)",
    department: "Surgical IPD",
    payScale: "9300-34800 GP 5400",
    photo: P[1],
  },
  {
    id: "h59",
    name: "Dr. Dahake Saloni Bhaskar",
    fatherName: "Bhaskar",
    qualification: "BAMS",
    dateOfAppointment: "02-08-2024",
    natureOfAppointment: "regular",
    designation: "RSO (Surgical)",
    department: "Surgical IPD",
    payScale: "9300-34800 GP 5400",
    photo: P[2],
  },
  {
    id: "h60",
    name: "Dhole Geeta Shyam",
    fatherName: "Shyam",
    qualification: "ANM",
    dateOfAppointment: "01-08-2023",
    natureOfAppointment: "regular",
    designation: "Panchakarma Nurse",
    department: "Staff Of Panchkarma / Therapist Section",
    payScale: "9300-34800 GP 4200",
    photo: P[3],
  },
  {
    id: "h61",
    name: "Wankhede Sanghratna Subhash",
    fatherName: "Subhash",
    qualification: "B.A.",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Therapist (Male)",
    department: "Staff Of Panchkarma / Therapist Section",
    payScale: "9300-34800 GP 4200",
    photo: P[4],
  },
  {
    id: "h62",
    name: "Gupta Jitendra Chetram",
    fatherName: "Chetram",
    qualification: "HSC",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Therapist (Male)",
    department: "Staff Of Panchkarma / Therapist Section",
    payScale: "9300-34800 GP 4200",
    photo: P[5],
  },
  {
    id: "h63",
    name: "Borude Dnyaneshwar Madhukar",
    fatherName: "Madhukar",
    qualification: "HSC",
    dateOfAppointment: "01-09-2025",
    natureOfAppointment: "regular",
    designation: "Therapist (Male)",
    department: "Staff Of Panchkarma / Therapist Section",
    payScale: "9300-34800 GP 5400",
    photo: P[6],
  },
  {
    id: "h64",
    name: "Kaiwart Yukti Brahamarshi",
    fatherName: "Brahamarshi",
    qualification: "B.A.",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Therapist (Female)",
    department: "Staff Of Panchkarma / Therapist Section",
    payScale: "9300-34800 GP 4200",
    photo: P[7],
  },
  {
    id: "h65",
    name: "Raut Nikita Ashok",
    fatherName: "Ashok",
    qualification: "HSC",
    dateOfAppointment: "02-02-2026",
    natureOfAppointment: "regular",
    designation: "Therapist (Female)",
    department: "Staff Of Panchkarma / Therapist Section",
    payScale: "9300-34800 GP 4200",
    photo: P[0],
  },
  {
    id: "h66",
    name: "Dabhade Savita Ramesh",
    fatherName: "Ramesh",
    qualification: "SSC",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Therapist (Female)",
    department: "Staff Of Panchkarma / Therapist Section",
    payScale: "9300-34800 GP 4200",
    photo: P[1],
  },
  {
    id: "h67",
    name: "Dr. Lahane Om Arvind",
    fatherName: "Arvind",
    qualification: "BAMS",
    dateOfAppointment: "05-11-2018",
    natureOfAppointment: "Part Time",
    designation: "House Officer",
    department: "Staff Of Panchkarma / Therapist Section",
    payScale: "14000/- Fix",
    photo: P[2],
  },
  {
    id: "h68",
    name: "Jagdhane Nikita Rameshwar",
    fatherName: "Rameshwar",
    qualification: "ANM",
    dateOfAppointment: "01-04-2026",
    natureOfAppointment: "regular",
    designation: "Staff Nurse",
    department: "Operation Theater",
    payScale: "9300-34800 GP 4200",
    photo: P[3],
  },
  {
    id: "h69",
    name: "Vaidya Yogesh Vijay",
    fatherName: "Vijay",
    qualification: "HSC",
    dateOfAppointment: "11-01-2025",
    natureOfAppointment: "regular",
    designation: "Operation Theater Attendent",
    department: "Operation Theater",
    payScale: "4440-7440 GP 1800",
    photo: P[4],
  },
  {
    id: "h70",
    name: "Ghode Yash Sudhakar",
    fatherName: "Sudhakar",
    qualification: "HSC",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Operation Theater Attendent",
    department: "Operation Theater",
    payScale: "4440-7440 GP 1300",
    photo: P[5],
  },
  {
    id: "h71",
    name: "Gawai Ravina Ganesh",
    fatherName: "Ganesh",
    qualification: "ANM",
    dateOfAppointment: "01-04-2026",
    natureOfAppointment: "regular",
    designation: "Staff Nurse",
    department: "Labour Room",
    payScale: "9300-34800 GP 4200",
    photo: P[6],
  },
  {
    id: "h72",
    name: "Khodake Chaitali Vasanta",
    fatherName: "Vasanta",
    qualification: "ANM",
    dateOfAppointment: "01-04-2026",
    natureOfAppointment: "regular",
    designation: "Staff Nurse",
    department: "Labour Room",
    payScale: "9300-34800 GP 4200",
    photo: P[7],
  },
  {
    id: "h73",
    name: "Turukmane Maya Pandurang",
    fatherName: "Pandurang",
    qualification: "ANM",
    dateOfAppointment: "01-04-2026",
    natureOfAppointment: "regular",
    designation: "Staff Nurse",
    department: "Labour Room",
    payScale: "9300-34800 GP 4200",
    photo: P[0],
  },
  {
    id: "h74",
    name: "Chandalne Asha Balu",
    fatherName: "Balu",
    qualification: "Not Applicable",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "MTS Female",
    department: "Labour Room",
    payScale: "4440-7440 GP 1600",
    photo: P[1],
  },
  {
    id: "h75",
    name: "Nikam Komal Vishnu",
    fatherName: "Vishnu",
    qualification: "HSC",
    dateOfAppointment: "01-04-2026",
    natureOfAppointment: "regular",
    designation: "MTS Female",
    department: "Labour Room",
    payScale: "4440-7440 GP 1880",
    photo: P[2],
  },
  {
    id: "h76",
    name: "Khadse Neha Ganesh",
    fatherName: "Ganesh",
    qualification: "HSC",
    dateOfAppointment: "01-04-2026",
    natureOfAppointment: "regular",
    designation: "MTS Female",
    department: "Labour Room",
    payScale: "4440-7440 GP 1880",
    photo: P[3],
  },
  {
    id: "h77",
    name: "Dr. Wayal Vaishnavi Prabhakar",
    fatherName: "Prabhakar",
    qualification: "MBBS",
    dateOfAppointment: "01-07-2024",
    natureOfAppointment: "Part Time",
    designation: "Physiotherapist",
    department: "Physiotherapy",
    payScale: "14000/- Fix",
    photo: P[4],
  },
  {
    id: "h78",
    name: "Gade Gopal Janardhan",
    fatherName: "Janardhan",
    qualification: "HSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Attendent / Ayah",
    department: "Physiotherapy",
    payScale: "9300-34800 GP 4200",
    photo: P[5],
  },
  {
    id: "h79",
    name: "Dr. Wakode Premraj Bhimrao",
    fatherName: "Bhimrao",
    qualification: "Certificate course in Yoga",
    dateOfAppointment: "03-11-2018",
    natureOfAppointment: "Part Time",
    designation: "Yoga Demonstrator",
    department: "Yoga",
    payScale: "14000 /- Fix",
    photo: P[6],
  },
  {
    id: "h80",
    name: "Dr. Shendge Pallavi Sudhir",
    fatherName: "Sudhir",
    qualification: "BAMS, MD(Swasthavritta)",
    dateOfAppointment: "16-03-2026",
    natureOfAppointment: "regular",
    designation: "Pathya Incharge",
    department: "Pathya Diet Section",
    payScale: "15600-39100 GP 6000",
    photo: P[7],
  },
  {
    id: "h81",
    name: "Anamika Gopalsingh Jodha Rathore",
    fatherName: "Gopalsingh",
    qualification: "BA",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Pathya Cook",
    department: "Pathya Diet Section",
    payScale: "4440-7440 GP 1600",
    photo: P[0],
  },
  {
    id: "h82",
    name: "Dabhade Ramesh Aashruba",
    fatherName: "Aashruba",
    qualification: "HSC",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Pathya Cook",
    department: "Pathya Diet Section",
    payScale: "9300-34800 GP 4200",
    photo: P[1],
  },
  {
    id: "h83",
    name: "Kakde Shravan Madanrao",
    fatherName: "Madanrao",
    qualification: "HSC",
    dateOfAppointment: "03-11-2018",
    natureOfAppointment: "regular",
    designation: "MTS",
    department: "Pathya Diet Section",
    payScale: "5200-20200 GP 1900",
    photo: P[2],
  },
  {
    id: "h84",
    name: "Deshmukh Prem Sanjay",
    fatherName: "Sanjay",
    qualification: "HSC",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "MTS",
    department: "Pathya Diet Section",
    payScale: "4440-7440 GP 1850",
    photo: P[3],
  },
  {
    id: "h85",
    name: "Dr. Gaikwad Anil Shankar",
    fatherName: "Shankar",
    qualification: "MBBS, MD",
    dateOfAppointment: "05-11-2018",
    natureOfAppointment: "Part Time",
    designation: "Medical Specialist",
    department: "Modern Medical Staff",
    payScale: "14000/- Fix",
    photo: P[4],
  },
  {
    id: "h86",
    name: "Dr. Rathod Prashant Galsing",
    fatherName: "Galsing",
    qualification: "MBBS, MS",
    dateOfAppointment: "05-11-2018",
    natureOfAppointment: "Part Time",
    designation: "Surgical Specialist",
    department: "Modern Medical Staff",
    payScale: "14000/- Fix",
    photo: P[5],
  },
  {
    id: "h87",
    name: "Dr. Bhagat Dipak Dattu",
    fatherName: "Dattu",
    qualification: "MBBS, TDD",
    dateOfAppointment: "01-07-2024",
    natureOfAppointment: "Part Time",
    designation: "Obstetrician and Gynaecologist",
    department: "Modern Medical Staff",
    payScale: "14000/- Fix",
    photo: P[6],
  },
  {
    id: "h88",
    name: "Dr. Morwal Swapnil Surendra",
    fatherName: "Surendra",
    qualification: "MBBS, MD",
    dateOfAppointment: "01-07-2024",
    natureOfAppointment: "Part Time",
    designation: "Opthalmologist",
    department: "Modern Medical Staff",
    payScale: "14000/- Fix",
    photo: P[7],
  },
  {
    id: "h89",
    name: "Dr. Narwade Ashish Hanumantrao",
    fatherName: "Hanumantrao",
    qualification: "MBBS, MD",
    dateOfAppointment: "03-11-2018",
    natureOfAppointment: "Part Time",
    designation: "Pediatrician",
    department: "Modern Medical Staff",
    payScale: "14000/- Fix",
    photo: P[0],
  },
  {
    id: "h90",
    name: "Dr. Joshi Amit Arun",
    fatherName: "Arun",
    qualification: "BDS",
    dateOfAppointment: "03-11-2018",
    natureOfAppointment: "Part Time",
    designation: "Dentist",
    department: "Modern Medical Staff",
    payScale: "14000/- Fix",
    photo: P[1],
  },
],
  
 "non-teaching": [
  {
    id: "n1",
    name: "Vinod Sahebrao Pandhare",
    fatherName: "Sahebrao",
    qualification: "B.Sc , B.Ed",
    dateOfAppointment: "03-02-2025",
    natureOfAppointment: "regular",
    designation: "Office Superintendent",
    department: "Administration",
    payScale: "9300-34800 GP-4400",
    photo: P[0],
  },
  {
    id: "n2",
    name: "Sachin Achyutrao Mhaske",
    fatherName: "Achyutrao",
    qualification: "B.A.",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "PA to Principal",
    department: "Administration",
    payScale: "9300-34800 GP-4400",
    photo: P[1],
  },
  {
    id: "n3",
    name: "Santosh Vishnu Mate",
    fatherName: "Vishnu",
    qualification: "B.Sc",
    dateOfAppointment: "02-11-2020",
    natureOfAppointment: "regular",
    designation: "Clerk",
    department: "Administration",
    payScale: "9300-34800 GP-4400",
    photo: P[2],
  },
  {
    id: "n4",
    name: "Ajay Hiralal Banchare",
    fatherName: "Hiralal",
    qualification: "B.A.",
    dateOfAppointment: "03-10-2023",
    natureOfAppointment: "regular",
    designation: "Clerk",
    department: "Administration",
    payScale: "4440-7440 GP-1300",
    photo: P[3],
  },
  {
    id: "n5",
    name: "Mohan Pralhad Dhadve",
    fatherName: "Pralhad",
    qualification: "M.A.",
    dateOfAppointment: "03-10-2023",
    natureOfAppointment: "regular",
    designation: "Clerk",
    department: "Administration",
    payScale: "9300-34800 GP-4400",
    photo: P[4],
  },
  {
    id: "n6",
    name: "Ganesh Samadhan Nikas",
    fatherName: "Samadhan",
    qualification: "M.A.",
    dateOfAppointment: "05-11-2020",
    natureOfAppointment: "regular",
    designation: "Clerk",
    department: "Administration",
    payScale: "5200-20200 GP-1900",
    photo: P[5],
  },
  {
    id: "n7",
    name: "Ashwini Prakash Nagrik",
    fatherName: "Prakash",
    qualification: "B.Com",
    dateOfAppointment: "03-10-2023",
    natureOfAppointment: "regular",
    designation: "Accountant",
    department: "Administration",
    payScale: "9300-34800 GP-4400",
    photo: P[6],
  },
  {
    id: "n8",
    name: "Sumedh Rajendra Panad",
    fatherName: "Rajendra",
    qualification: "B.Sc",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Clerk",
    department: "Account Section",
    payScale: "9300-34800 GP-4400",
    photo: P[7],
  },
  {
    id: "n9",
    name: "Rahul Digambar Pawar",
    fatherName: "Digambar",
    qualification: "B.A.",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Clerk",
    department: "Account Section",
    payScale: "9300-34800 GP-4400",
    photo: P[0],
  },
  {
    id: "n10",
    name: "Sunita Umesh Bangar",
    fatherName: "Umesh",
    qualification: "HSC",
    dateOfAppointment: "16-06-2026",
    natureOfAppointment: "regular",
    designation: "Multi Tasking Staff",
    department: "Administration",
    payScale: "4440-7440 GP-1300",
    photo: P[1],
  },
  {
    id: "n11",
    name: "Anil Sitaram Chikhalekar",
    fatherName: "Sitaram",
    qualification: "9th",
    dateOfAppointment: "09-11-2020",
    natureOfAppointment: "regular",
    designation: "Multi Tasking Staff",
    department: "Administration",
    payScale: "4440-7440 GP-1300",
    photo: P[2],
  },
  {
    id: "n12",
    name: "Abhishek Dagduji Mule",
    fatherName: "Dagduji",
    qualification: "HSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Multi Tasking Staff",
    department: "Administration",
    payScale: "9300-34800 GP-4200",
    photo: P[3],
  },
  {
    id: "n13",
    name: "Shaikh Shakil Shaikh Shabbir",
    fatherName: "Shaikh Shabbir",
    qualification: "SSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Multi Tasking Staff",
    department: "Administration",
    payScale: "9300-34800 GP-4200",
    photo: P[4],
  },
  {
    id: "n14",
    name: "Sumit Gajanan Gawai",
    fatherName: "Gajanan",
    qualification: "M.Sc(Computer Science)",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "IT Officer",
    department: "IT Cell",
    payScale: "15600-39100 GP 5400",
    photo: P[5],
  },
  {
    id: "n15",
    name: "Samir Salim Shaikh",
    fatherName: "Salim",
    qualification: "B.Tech Computer Science",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "IT Assistant",
    department: "IT Cell",
    payScale: "9300-34800 GP-4200",
    photo: P[6],
  },
  {
    id: "n16",
    name: "Pramod Pralhad Murudkar",
    fatherName: "Pralhad",
    qualification: "M.Lib",
    dateOfAppointment: "13-01-2025",
    natureOfAppointment: "regular",
    designation: "Librarian",
    department: "Central Library",
    payScale: "9300-34800 GP-5400",
    photo: P[7],
  },
  {
    id: "n17",
    name: "Varad Shankar Thakur",
    fatherName: "Shankar",
    qualification: "B.Lib",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Asst.Librarian",
    department: "Central Library",
    payScale: "9300-34800 GP-4400",
    photo: P[0],
  },
  {
    id: "n18",
    name: "Nagesh Omshiva Bore",
    fatherName: "Omshiva",
    qualification: "B.Lib",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Library Attendent",
    department: "Central Library",
    payScale: "4440-7440 GP-1300",
    photo: P[1],
  },
  {
    id: "n19",
    name: "Rushikesh Sanjay Metangale",
    fatherName: "Sanjay",
    qualification: "9th",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Multi Tasking Staff",
    department: "Central Library",
    payScale: "4440-7440 GP-1300",
    photo: P[2],
  },
  {
    id: "n20",
    name: "Vd. Ashish Naresh Jaiswal",
    fatherName: "Naresh",
    qualification: "BAMS , MD",
    dateOfAppointment: "01-09-2025",
    natureOfAppointment: "regular",
    designation: "Incharge Yogya-Clinical Skill or Simulation Laboratory",
    department: "Yogya-Clinical Skill or Simulation Laboratory",
    payScale: "37400-67000 GP 10000",
    photo: P[3],
  },
  {
    id: "n21",
    name: "Pavan Kundlikrao Deshmukh",
    fatherName: "Kundlikrao",
    qualification: "M.A.",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Clerk",
    department: "Yogya-Clinical Skill or Simulation Laboratory",
    payScale: "9300-34800 GP-4400",
    photo: P[4],
  },
  {
    id: "n22",
    name: "Sanket Gulab Sapkal",
    fatherName: "Gulab",
    qualification: "HSC",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Multi Tasking Staff",
    department: "Yogya-Clinical Skill or Simulation Laboratory",
    payScale: "4440-7440 GP-1300",
    photo: P[5],
  },
  {
    id: "n23",
    name: "Vinod Sahebrao Pandhare",
    fatherName: "Sahebrao",
    qualification: "B.Sc , B.Ed",
    dateOfAppointment: "03-02-2025",
    natureOfAppointment: "regular",
    designation: "Incharge Human Resource Development cell",
    department: "Human Resource Development cell",
    payScale: "9300-34800 GP-4400",
    photo: P[6],
  },
  {
    id: "n24",
    name: "Tejaswini Gopal Gaikwad",
    fatherName: "Gopal",
    qualification: "B.Sc",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Clerk",
    department: "Human Resource Development cell",
    payScale: "9300-34800 GP-4400",
    photo: P[7],
  },
  {
    id: "n25",
    name: "Yash Santosh Wayal",
    fatherName: "Santosh",
    qualification: "HSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Multi Tasking Staff",
    department: "Human Resource Development cell",
    payScale: "4440-7440 GP-1300",
    photo: P[0],
  },
  {
    id: "n26",
    name: "Santosh Tukaram Mhaske",
    fatherName: "Tukaram",
    qualification: "B.E.(E&TC)",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Clerk",
    department: "Samhita Siddhant",
    payScale: "9300-34800 GP-4400",
    photo: P[1],
  },
  {
    id: "n27",
    name: "Asha Prakash Mairal",
    fatherName: "Prakash",
    qualification: "7th",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Multi Tasking Staff",
    department: "Samhita Siddhant",
    payScale: "4440-7440 GP-1300",
    photo: P[2],
  },
  {
    id: "n28",
    name: "Durgesh Suresh Gudadhe",
    fatherName: "Suresh",
    qualification: "HSC",
    dateOfAppointment: "02-06-2025",
    natureOfAppointment: "regular",
    designation: "Cadaver Lifter",
    department: "Rachana Sharir",
    payScale: "9300-34800 GP-4200",
    photo: P[3],
  },
  {
    id: "n29",
    name: "Shivaji Keshav Wayal",
    fatherName: "Keshav",
    qualification: "HSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Attendent cum museum Keeper",
    department: "Rachana Sharir",
    payScale: "4440-7440 GP-1300",
    photo: P[4],
  },
  {
    id: "n30",
    name: "Shubham Bhagwan Dhote",
    fatherName: "Bhagwan",
    qualification: "B.Sc",
    dateOfAppointment: "03-10-2023",
    natureOfAppointment: "regular",
    designation: "Lab Technician",
    department: "Kriya Sharir",
    payScale: "9300-34800 GP-4200",
    photo: P[5],
  },
  {
    id: "n31",
    name: "Saurabh Rajesh Dandade",
    fatherName: "Rajesh",
    qualification: "HSC",
    dateOfAppointment: "03-04-2023",
    natureOfAppointment: "regular",
    designation: "Lab Attendent",
    department: "Kriya Sharir",
    payScale: "4440-7440 GP-1300",
    photo: P[6],
  },
  {
    id: "n32",
    name: "Vaishnavi Shivhari Shejul",
    fatherName: "Shivhari",
    qualification: "B.Pharm",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Pharmacognosist",
    department: "Dravyaguna Vigyan",
    payScale: "15600-39100 GP 6000",
    photo: P[7],
  },
  {
    id: "n33",
    name: "Dhiraj Prakash Mairal",
    fatherName: "Prakash",
    qualification: "HSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Lab Attendent",
    department: "Dravyaguna Vigyan",
    payScale: "4440-7440 GP-1300",
    photo: P[0],
  },
  {
    id: "n34",
    name: "Dipak Bhagwan Shelke",
    fatherName: "Bhagwan",
    qualification: "Diploma",
    dateOfAppointment: "15-07-2024",
    natureOfAppointment: "regular",
    designation: "Gardener",
    department: "Dravyaguna Vigyan",
    payScale: "4440-7440 GP-1300",
    photo: P[1],
  },
  {
    id: "n35",
    name: "Vrushali Shrihari Borey",
    fatherName: "Shrihari",
    qualification: "B.Pharm",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Instructor (B.Pharm)",
    department: "Rasashashtra & B.K.",
    payScale: "15600-39100 GP 6000",
    photo: P[2],
  },
  {
    id: "n36",
    name: "Rajkumar Uttam Dotonde",
    fatherName: "Uttam",
    qualification: "HSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Lab Attendent cum museum keeper",
    department: "Rasashashtra & B.K.",
    payScale: "4440-7440 GP-1300",
    photo: P[3],
  },
  {
    id: "n37",
    name: "Jaymala Ashok Rathod",
    fatherName: "Ashok",
    qualification: "B.Pharm",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Analytical Chemist (B.Pharm)",
    department: "Quality Control Lab",
    payScale: "15600-39100 GP 6000",
    photo: P[4],
  },
  {
    id: "n38",
    name: "Bhagwat Eknath Jeughale",
    fatherName: "Eknath",
    qualification: "B.A.",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Clerk",
    department: "Quality Control Lab",
    payScale: "9300-34800 GP-4400",
    photo: P[5],
  },
  {
    id: "n39",
    name: "Ramprasad Ramesh Dabhade",
    fatherName: "Ramesh",
    qualification: "HSC",
    dateOfAppointment: "02-05-2026",
    natureOfAppointment: "regular",
    designation: "Lab Attendent",
    department: "Quality Control Lab",
    payScale: "4440-7440 GP-1300",
    photo: P[6],
  },
  {
    id: "n40",
    name: "Pradip Ashok Dutonde",
    fatherName: "Ashok",
    qualification: "DLMT",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Lab Technician (DMLT)",
    department: "Rog Nidan",
    payScale: "9300-34800 GP-4400",
    photo: P[7],
  },
  {
    id: "n41",
    name: "Saurabh Nandkishor Bodkhe",
    fatherName: "Nandkishor",
    qualification: "HSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Lab Attendent",
    department: "Rog Nidan",
    payScale: "4440-7440 GP-1300",
    photo: P[0],
  },
  {
    id: "n42",
    name: "Sahil Gajanan Bodkhe",
    fatherName: "Gajanan",
    qualification: "HSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Lab Technician (12th Sci)",
    department: "Agad Tantra",
    payScale: "9300-34800 GP-4400",
    photo: P[1],
  },
  {
    id: "n43",
    name: "Pravin Bhimrao Gawai",
    fatherName: "Bhimrao",
    qualification: "HSC",
    dateOfAppointment: "03-12-2020",
    natureOfAppointment: "regular",
    designation: "Lab Attendent cum museum keeper",
    department: "Agad Tantra",
    payScale: "5200-20200 GP-1900",
    photo: P[2],
  },
  {
    id: "n44",
    name: "Nikhilkumar Vinodkumar Jogad",
    fatherName: "Vinodkumar",
    qualification: "HSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Lab Technician (12th Sci)",
    department: "Swasthavritta",
    payScale: "9300-34800 GP-4400",
    photo: P[3],
  },
  {
    id: "n45",
    name: "Prashant Kacharu Suradkar",
    fatherName: "Kacharu",
    qualification: "SSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Lab Attendent cum museum keeper",
    department: "Swasthavritta",
    payScale: "4440-7440 GP-1300",
    photo: P[4],
  },
  {
    id: "n46",
    name: "Anjali Ramesh Johare",
    fatherName: "Ramesh",
    qualification: "DNYS",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Yoga Instructor",
    department: "Swasthavritta",
    payScale: "9300-34800 GP-4400",
    photo: P[5],
  },
  {
    id: "n47",
    name: "Sachin Gajanan Tale",
    fatherName: "Gajanan",
    qualification: "MBA",
    dateOfAppointment: "04-03-2026",
    natureOfAppointment: "regular",
    designation: "Co-Ordinator",
    department: "Internal Quality Assurance Cell",
    payScale: "9300-34800 GP 4200",
    photo: P[6],
  },
  {
    id: "n48",
    name: "Krushna Namdeorao Deshmukh",
    fatherName: "Namdeorao",
    qualification: "M.A.",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Clerk",
    department: "Internal Quality Assurance Cell",
    payScale: "9300-34800 GP-4400",
    photo: P[7],
  },
  {
    id: "n49",
    name: "Antkala Uttam Kokate",
    fatherName: "Uttam",
    qualification: "7th",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Multi Tasking Staff",
    department: "Internal Quality Assurance Cell",
    payScale: "4440-7440 GP-1300",
    photo: P[0],
  },
  {
    id: "n50",
    name: "Ravi Dhondu Lokhande",
    fatherName: "Dhondu",
    qualification: "B.PEd",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "Part Time",
    designation: "Physical Education Instructor",
    department: "Co and Extra curricular activities",
    payScale: "9300-34800 GP 4200",
    photo: P[1],
  },
  {
    id: "n51",
    name: "Kavita Shyam Wasavkar",
    fatherName: "Shyam",
    qualification: "7th",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Multi Tasking Staff",
    department: "Co and Extra curricular activities",
    payScale: "4440-7440 GP-1300",
    photo: P[2],
  },
  {
    id: "n52",
    name: "Chandan Nandkumar Dhongade",
    fatherName: "Nandkumar",
    qualification: "B.Com",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "Part Time",
    designation: "Councillor",
    department: "Student Support & Career Guidance Cell",
    payScale: "9300-34800 GP 4200",
    photo: P[3],
  },
  {
    id: "n53",
    name: "Ajinkya Nandkishor Mapari",
    fatherName: "Nandkishor",
    qualification: "B.E.(Civil)",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "Part Time",
    designation: "Site Engineer",
    department: "Central Workshop or Maintenance cell",
    payScale: "9300-34800 GP 4200",
    photo: P[4],
  },
  {
    id: "n54",
    name: "Shaikh Gaffar Shaikh Ibrahim",
    fatherName: "Shaikh Ibrahim",
    qualification: "ITI",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "Part Time",
    designation: "Electrician",
    department: "Central Workshop or Maintenance cell",
    payScale: "9300-34800 GP 4200",
    photo: P[5],
  },
  {
    id: "n55",
    name: "Yogesh Ghanshyam Ankushkar",
    fatherName: "Ghanshyam",
    qualification: "ITI",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "Part Time",
    designation: "Plumber",
    department: "Central Workshop or Maintenance cell",
    payScale: "9300-34800 GP 4200",
    photo: P[6],
  },
  {
    id: "n56",
    name: "Nitesh Parmeshwar Jangid",
    fatherName: "Parmeshwar",
    qualification: "HSC",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "Part Time",
    designation: "Carpenter",
    department: "Central Workshop or Maintenance cell",
    payScale: "9300-34800 GP 4200",
    photo: P[7],
  },
  {
    id: "n57",
    name: "Ashabai Shivaji Wathore",
    fatherName: "Shivaji",
    qualification: "7th",
    dateOfAppointment: "02-03-2026",
    natureOfAppointment: "regular",
    designation: "Multi Tasking Staff",
    department: "Central Workshop or Maintenance cell",
    payScale: "4440-7440 GP-1300",
    photo: P[0],
  },
  {
    id: "n58",
    name: "Manesh Vasanta Ambhore",
    fatherName: "Vasanta",
    qualification: "B.Pharm",
    dateOfAppointment: "01-04-2026",
    natureOfAppointment: "regular",
    designation: "Clerk",
    department: "Store",
    payScale: "9300-34800 GP-4400",
    photo: P[1],
  },
  {
    id: "n59",
    name: "Kundan Narayan Debaje",
    fatherName: "Narayan",
    qualification: "HSC",
    dateOfAppointment: "01-04-2026",
    natureOfAppointment: "regular",
    designation: "Multi Tasking Staff",
    department: "Store",
    payScale: "4440-7440 GP-1300",
    photo: P[2],
  },
],
  
  teaching: [
    {
      id: "t1",
      name: "Dr. Milind Aware",
      fatherName: "Shri Ramdas Aware",
      qualification: "M.D. Ph.D. (Ayurveda)",
      dateOfAppointment: "01/07/2008",
      natureOfAppointment: "regular",
      designation: "Professor",
      department: "Kayachikitsa",
      payScale: "Level 14 (₹1,44,200 - ₹2,18,200)",
      photo: P[4],
      education: "M.D. Ph.D. (Ayurveda)",
      year: "Since 2008",
      mobile: "+91 98200 40001",
      email: "milind.aware@rajashriayurvedic.edu.in",
      teacherCode: "TCH001",
      dob: "15/06/1975",
      registrationNumber: "NCISM-12345",
      dateOfJoining: "01/07/2008",
      experience: "17 years",
    },
    {
      id: "t2",
      name: "Dr. Dineshwar Daware",
      fatherName: "Shri Suresh Daware",
      qualification: "M.D. (Samhita Siddhanta)",
      dateOfAppointment: "15/07/2012",
      natureOfAppointment: "regular",
      designation: "Professor",
      department: "Samhita Siddhanta",
      payScale: "Level 14 (₹1,44,200 - ₹2,18,200)",
      photo: P[5],
      education: "M.D. (Samhita Siddhanta)",
      year: "Since 2012",
      mobile: "+91 98200 40002",
      email: "dineshwar.daware@rajashriayurvedic.edu.in",
      teacherCode: "TCH002",
      dob: "20/08/1980",
      registrationNumber: "NCISM-67890",
      dateOfJoining: "15/07/2012",
      experience: "12 years",
    },
    {
      id: "t3",
      name: "Dr. Priya Patil",
      fatherName: "Shri Anil Patil",
      qualification: "M.D. (Panchakarma)",
      dateOfAppointment: "01/09/2015",
      natureOfAppointment: "regular",
      designation: "Associate Professor",
      department: "Panchakarma",
      payScale: "Level 13 (₹1,23,100 - ₹2,15,900)",
      photo: P[6],
      education: "M.D. (Panchakarma)",
      year: "Since 2015",
      mobile: "+91 98200 40003",
      email: "priya.patil@rajashriayurvedic.edu.in",
      teacherCode: "TCH003",
      dob: "10/12/1985",
      registrationNumber: "NCISM-24680",
      dateOfJoining: "01/09/2015",
      experience: "9 years",
    },
    {
      id: "t4",
      name: "Dr. Ramesh Wagh",
      fatherName: "Shri Mohan Wagh",
      qualification: "M.D. (Dravyaguna)",
      dateOfAppointment: "01/01/2018",
      natureOfAppointment: "regular",
      designation: "Associate Professor",
      department: "Dravyaguna",
      payScale: "Level 13 (₹1,23,100 - ₹2,15,900)",
      photo: P[7],
      education: "M.D. (Dravyaguna)",
      year: "Since 2018",
      mobile: "+91 98200 40004",
      email: "ramesh.wagh@rajashriayurvedic.edu.in",
      teacherCode: "TCH004",
      dob: "05/03/1982",
      registrationNumber: "NCISM-13579",
      dateOfJoining: "01/01/2018",
      experience: "6 years",
    },
    {
      id: "t5",
      name: "Dr. Swati Kulkarni",
      fatherName: "Shri Prakash Kulkarni",
      qualification: "M.D. (Kaumarabhritya)",
      dateOfAppointment: "10/06/2020",
      natureOfAppointment: "contractual",
      designation: "Assistant Professor",
      department: "Kaumarabhritya",
      payScale: "Level 12 (₹78,800 - ₹2,09,200)",
      photo: P[0],
      education: "M.D. (Kaumarabhritya)",
      year: "Since 2020",
      mobile: "+91 98200 40005",
      email: "swati.kulkarni@rajashriayurvedic.edu.in",
      teacherCode: "TCH005",
      dob: "22/09/1990",
      registrationNumber: "NCISM-97531",
      dateOfJoining: "10/06/2020",
      experience: "4 years",
    },
  ],
};

const KEY = "ssam-staff-v1";
type Store = Partial<Record<StaffGroupKey, StaffMember[]>>;

function load(): Store {
  if (typeof window === "undefined") return {};
  try {
    const stored = localStorage.getItem(KEY);
    if (!stored) return {};
    return JSON.parse(stored);
  } catch {
    return {};
  }
}

function save(s: Store) {
  localStorage.setItem(KEY, JSON.stringify(s));
  window.dispatchEvent(new Event("staff-changed"));
}

export function getStaff(group: StaffGroupKey): StaffMember[] {
  const s = load();
  const stored = s[group];
  if (stored && stored.length > 0) {
    return stored;
  }
  return DEFAULTS[group];
}

export function setStaff(group: StaffGroupKey, members: StaffMember[]) {
  const s = load();
  s[group] = members;
  save(s);
}

export function resetStaff(group: StaffGroupKey) {
  const s = load();
  delete s[group];
  save(s);
}

export function useStaff(group: StaffGroupKey): StaffMember[] {
  const [list, setList] = useState<StaffMember[]>(() =>
    typeof window === "undefined" ? DEFAULTS[group] : getStaff(group),
  );
  useEffect(() => {
    const update = () => setList(getStaff(group));
    update();
    window.addEventListener("staff-changed", update);
    window.addEventListener("storage", update);
    return () => {
      window.removeEventListener("staff-changed", update);
      window.removeEventListener("storage", update);
    };
  }, [group]);
  return list;
}

export function newId() {
  return `m-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
}